### ISSUE TITLE
error starting server

### ISSUE THREAD

**Issue by ansalo1021** [mihailgaberov/bingo#22]
hi,
I have a problem whit starting server node.js 

C:\proyectosNode\bingo-master>node server.js
C:\proyectosNode\bingo-master\node_modules\express-jwt\lib\index.js:22
  if (!options.algorithms) throw new Error('algorithms should be set');
                           ^

Error: algorithms should be set
    at module.exports (C:\proyectosNode\bingo-master\node_modules\express-jwt\lib\index.js:22:34)
    at Object.<anonymous> (C:\proyectosNode\bingo-master\bingo-api\routes\index.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\proyectosNode\bingo-master\server.js:10:19)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
![node_bd](https://user-images.githubusercontent.com/88809335/129124526-1c9e7865-8d4b-48c9-b3c4-d1ae230a1be1.PNG)

**Comment by mihailgaberov** [comment]
Hi there, thank you for reaching out. This looks like you have some sort of an issue with your local packages. I have never met this before. Maybe you can try to delete your node_modules folder, make sure your Node.js version is Ok and then do a clean installation. Hope it helps.
