### ISSUE TITLE
Problem on logging into the game

### ISSUE THREAD

**Issue by cryptomadco** [mihailgaberov/bingo#8]
Hi .
I just followed the steps described in github page for installation. followed exactly every step but I have problem on logging in into the game .

I don't know if I need to change something for mongodb or not but seems the registration page do not work for me. also seems the login functionality is not working for me as I can not login into with the credentials I used during registration .

Do I need some default sort of user and password to login?

Thanks!

**Comment by cryptomadco** [comment]
Also, when I type `node server.js` command I receive the following errors :

```
C:\bingo-master\bingo-master>node server.js
Error: ENOENT: no such file or directory, open '.env'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at Object.config (C:\bingo-master\bingo-master\node_modules\dotenv\lib\main.js:30:37)
    at Object.<anonymous> (C:\bingo-master\bingo-master\server.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '.env'
}

C:\bingo-master\bingo-master\node_modules\mongoose\lib\connection.js:542
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
    ^
Error [MongooseError]: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at new MongooseError (C:\bingo-master\bingo-master\node_modules\mongoose\lib\error\mongooseError.js:10:11)
    at NativeConnection.Connection.openUri (C:\bingo-master\bingo-master\node_modules\mongoose\lib\connection.js:542:11)
    at Mongoose.connect (C:\bingo-master\bingo-master\node_modules\mongoose\lib\index.js:332:15)
    at Object.<anonymous> (C:\bingo-master\bingo-master\bingo-api\models\db.js:6:4)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\bingo-master\bingo-master\server.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  message: 'The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.',
  name: 'MongooseError'
}
```

**Comment by mihailgaberov** [comment]
Hi @cryptomadco ,

Thank you for contacting me. 

Regarding your second question, you need to have a .env file in your project main directory. It needs to have two variables - the password for your database, called DB_SECRET and the URI that leads to your local database. Here is an example:

DB_SECRET=mydatabasepassword
DB_URI=mongodb://127.0.0.1/bingo-bigul

**Comment by mihailgaberov** [comment]
After you have your .env in place, make sure you have both, server and gulp, running as well as your local MongoDB (via `mongod` command). When trying to signup or login, would you make some screenshots for me to see what is happening? Please do it with Chrome Dev tools opened to `Console` tab.

Let me know how it goes.

**Comment by mihailgaberov** [comment]
Just notices that the instructions in the README are outdated. Sorry about that, updating them right now.

**Comment by cryptomadco** [comment]
Thanks for your reply, before proceeding to the next step, I want to know, do I need some specific things to manage my MongoDB databases or your application automatically do making new database and set connection and such ?

Do I need specific package regarding mongo for nodejs for example to install maybe? if yes so how can I do that ?

Thanks!

**Comment by mihailgaberov** [comment]
You must have MongoDB installed locally. You may get the free edition from https://www.mongodb.com/download-center/community

Also, not mandatory, but could be useful if you want to do any direct actions to the database, to have Compass - https://www.mongodb.com/products/compass. Any other software for working with MongoDB also can do the job. 

When have it installed, I use MongoDB shell to start the server with 'mongod' command.

It's important to mention that, in my case, the DB data is located at C:/data/db/, if in your case is needed, you may use 'dbpath' param to specify it explicitly. Here you may find more info on how to use this command - https://docs.mongodb.com/manual/reference/program/mongod/

**Comment by cryptomadco** [comment]
Hi .
Thanks for comprehensive help, the problem has been solved. the problem was exactly from mongodb and the .evn file .

Thanks!

**Comment by mihailgaberov** [comment]
Glad it worked!

I will update the README file to include `.env` and `mongodb `stuff as well (just for future ourselves:)).
